### ISSUE TITLE
Failing Maven build on OS X 10.11.4

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/pdfparser#10]
Following the instructions in the README, I installed Maven 3.3.9 using Homebrew.

I then ran the command

```
mvn clean package
```

This resulted in the following error:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[5,28] package main.java.pdfParsers does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[6,28] package main.java.pdfParsers does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[7,25] package main.java.loaders does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[8,25] package main.java.loaders does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,17] cannot find symbol
  symbol:   class PdfToJsonConverter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,52] cannot find symbol
  symbol:   class PdfToJsonConverter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,75] cannot find symbol
  symbol:   class LocalPdfReader
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,17] cannot find symbol
  symbol:   class JsonToPdfWriter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,49] cannot find symbol
  symbol:   class JsonToPdfWriter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,69] cannot find symbol
  symbol:   class LocalPdfWriter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,17] cannot find symbol
  symbol:   class PdfToJsonConverter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,52] cannot find symbol
  symbol:   class PdfToJsonConverter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,75] cannot find symbol
  symbol:   class LocalPdfReader
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,17] cannot find symbol
  symbol:   class JsonToPdfWriter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,49] cannot find symbol
  symbol:   class JsonToPdfWriter
  location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,69] cannot find symbol
  symbol:   class LocalPdfWriter
  location: class main.java.PdfParser
[INFO] 16 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.225 s
[INFO] Finished at: 2016-04-27T17:24:08-07:00
[INFO] Final Memory: 17M/138M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pdfparser: Compilation failure: Compilation failure:
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[5,28] package main.java.pdfParsers does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[6,28] package main.java.pdfParsers does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[7,25] package main.java.loaders does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[8,25] package main.java.loaders does not exist
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,17] cannot find symbol
[ERROR] symbol:   class PdfToJsonConverter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,52] cannot find symbol
[ERROR] symbol:   class PdfToJsonConverter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[77,75] cannot find symbol
[ERROR] symbol:   class LocalPdfReader
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,17] cannot find symbol
[ERROR] symbol:   class JsonToPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,49] cannot find symbol
[ERROR] symbol:   class JsonToPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[82,69] cannot find symbol
[ERROR] symbol:   class LocalPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,17] cannot find symbol
[ERROR] symbol:   class PdfToJsonConverter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,52] cannot find symbol
[ERROR] symbol:   class PdfToJsonConverter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[103,75] cannot find symbol
[ERROR] symbol:   class LocalPdfReader
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,17] cannot find symbol
[ERROR] symbol:   class JsonToPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,49] cannot find symbol
[ERROR] symbol:   class JsonToPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] /Users/bengolder/projects/pdfparser/src/main/java/PdfParser.java:[106,69] cannot find symbol
[ERROR] symbol:   class LocalPdfWriter
[ERROR] location: class main.java.PdfParser
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by eplusminus** [comment]
I believe the problem is [this commit](https://github.com/rogerawad/pdfparser/commit/f1ac79af0d4990bc05d0e31eb344f2cd372fa387), which incorrectly added a package prefix of "main.java" to all of the classes.

@rogerawad, those directories are not supposed to be part of the Java package structure— Maven just expects all the (non-test) source files to be contained within `src/main/java`. In other words, if you have a package called `dog.cat`, the corresponding source directory would be `src/main/java/dog/cat` (and unit tests for that package would be in `src/test/java/dog/cat`). I'm guessing that maybe you tried loading the project into Eclipse and Eclipse did not set the source folders correctly— it looks like other people have encountered the same confusion, see [this Stack Overflow page](http://stackoverflow.com/questions/14788480/package-name-without-main-java-in-maven).

**Comment by bengolder** [comment]
This is now fixed!
